FROM archlinux/base:latest

RUN pacman --noconfirm -Syu && \
    pacman --noconfirm -S clang

ARG CMAKE_VERSION=3.15.4

RUN pacman --noconfirm -S make && \
    \
    set -x && \
    pacman --noconfirm -S wget && \
    wget -qO- https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz | tar -xvzf - -C /opt/ && \
    echo "export PATH=\${PATH}:/opt/cmake-${CMAKE_VERSION}-Linux-x86_64/bin" >> ~/.bash_profile && \
    \
    pacman --noconfirm -S python python-pip && \
    pip3 install conan

