FROM ubuntu:18.04

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y clang 

RUN apt-get install -y make && \
    \
    apt-get install -y apt-transport-https ca-certificates gnupg software-properties-common wget && \
    wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add - && \
    apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' && \
    apt-get install kitware-archive-keyring && \
    apt-key --keyring /etc/apt/trusted.gpg del C1F34CDD40CD72DA && \
    apt-get install -y cmake && \
    \
    apt-get install -y python3 python3-pip && \
    pip3 install --user conan && \
    echo "export PATH=~/.local/bin:\$PATH" >> ~/.profile
    
