jobs:
  include:
    - stage: build
      os: linux
      language: python
      python: "3.7"
      compiler:
        - clang
        - gcc
      install: 
        - pip install conan
        - curl -sSL https://github.com/Kitware/CMake/releases/download/v3.14.7/cmake-3.14.7-Linux-x86_64.tar.gz | sudo tar -xzC /opt
      script:
        - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
        - conan remote list
        - mkdir build && cd build && cmake --configure .. -DCMAKE_BUILD_TYPE=debug && cmake --build .
        - ctest --verbose .
    - stage: build
      os: osx
      language: shell
      install:
        - brew update --quiet
        - echo 'brew "python"' > ./Brewfile
        - echo 'brew "cmake"' >> ./Brewfile
        - brew bundle --file=./Brewfile # installs python3 and cmake
        - pip install conan # install conan, python already needed
        - cmake --version
        - conan --version
      script:
        - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
        - conan remote list
        - mkdir build && cd build && cmake --configure .. -DCMAKE_BUILD_TYPE=debug && cmake --build .
        - ctest --verbose .
